export * from './shared';
export * from './landing';
export * from './order';
export * from './delivery';
export * from './about';
export * from './shop';
export * from './events';
export * from './footer';
export * from './largeOrders';
